spring.application.name=praktikum2

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url =jdbc:mysql://localhost:3308/spring?
spring.datasource.username =root
spring.datasource.password =MySqlaku123
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver

spring.config.import=optional:file:.env
server.port=8081